# CI test image for unit/lint/type tests
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:v2-automator-driver-cli as expo-maze-runner

COPY /test/expo /app/test/expo
WORKDIR /app/test/expo
